[build]
publish = "public"
command = "sh do hugo-development"

[build.environment]
HUGO_VERSION = "0.121.1"

[context.production]
publish = "public"
command = "sh do hugo"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"